name: opsmodelviewer
channels:
  - defaults
dependencies:
  - python=3.8
  - bokeh=2.0
  - pandas
  # Documentation
  - sphinx
  - doc8
  # Development
  - ipython
  - line_profiler
  - yapf
  - pytest
  - invoke
  - pip
  - pip:
    - "-e ."
