name: opsmodelviewer
channels:
  - defaults
dependencies:
  - python
  - bokeh
  # Documentation
  - sphinx
  - doc8
  # Development
  - ipython
  - line_profiler
  - yapf
  - pytest
  - invoke
  - pip
  - pip:
    - "-e ."
